name: Auto Merge PRs

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge PR if no conflicts
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
          git fetch origin $GITHUB_HEAD_REF:$GITHUB_HEAD_REF

          # Check if there are any merge conflicts
          if git merge-base --is-ancestor $GITHUB_HEAD_REF $GITHUB_BASE_REF; then
            git merge --ff-only $GITHUB_HEAD_REF
            git push origin HEAD:refs/heads/$GITHUB_BASE_REF
          else
            echo "Merge conflict detected. Manual intervention required."
          fi
        env:
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GITHUB_BASE_REF: ${{ github.base_ref }}
